//UPDATE PART. MAYBE NAME OF GROUP? IF YOU ARE THE ONE WHO HAV MADE IT
//NOTICE!!!!!!!!!!!!!!!!!!!YOU SHOULD GET NOT ONLY GROUPBTE BUT ALSO OLDGOURPNAME
//WHEN YOU USE UPDATE-GROUPNAME AND UPDATE-GROUPDESCRIPT FUNCTION!!!!!!